### PR TITLE
Standardize chart styling

### LINKED ISSUE #114: Colour scheme slightly varies between charts
**Describe the bug**
In the charts, the legends has slightly different styles between graphs. That includes, the legend for the blue data, the legend for the red target, and possibly the blue data line and red target line themselves too.

**To Reproduce**
1. Go to Defence tab, see the blue box to indicate the data label
2. Go to Immigration tab, see that the blue box is slightly darker

**Screenshots**
Image
Image

**Expected behavior**
At a minimum, it should all look the same.

Ideally we could move these styles to variables so that this issue doesn't happen

### PR DESCRIPTION
**Pull request by rmarescu**
Resolves #114

### CODE REVIEW

File: components/charts/AnnualizedHousingChart.tsx [hunk 1]
```diff
@@ -36,33 +38,7 @@ interface AnnualizedHousingChartProps {
...
-  label: string;
-  data: number[];
-  backgroundColor: string;
-  borderColor?: string;
-  borderWidth?: number;
-  hoverBackgroundColor?: string;
-}
-
-// Type for line dataset
-interface LineDataset {
```
Comment (rmarescu) [inline components/charts/AnnualizedHousingChart.tsx:51]: This and all the duplicates from the other files have been consolidated below, where it uses the interface from Chart.js https://github.com/BuildCanada/OutcomeTracker/blob/a998720f7f9a30fbee9d2d5d318baf4afe84385c/components/charts/types.ts#L9

File: components/charts/utils/styling.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+  tension: 0,
+  ...options,
+});
+
+/**
+ * Get standard styling for trend/moving average lines (red color scheme)
+ * @param options - Optional properties to override defaults
+ * @returns Style object for trend datasets
+ */
+export const getTrendLineStyling = (options: Partial<LineChartDataset> = {}): Partial<LineChartDataset> => ({
```
Comment (rmarescu) [inline components/charts/utils/styling.ts:36]: Trend line doesn't seem to be visible on any of the charts at this moment. I've enabled it manually on local, the legend looks like this:

Image

**Review by rmarescu — COMMENTED** [review]
@melkuo this PR should fix the inconsistent styling you've noticed, and also some other improvements, commented below. Please let me know what you think!

File: components/charts/AnnualizedHousingChart.tsx [hunk 3]
```diff
@@ -262,7 +228,7 @@ export default function AnnualizedHousingChart({
         position: "relative",
       }}
     >
-      <Chart type="bar" data={chartData} options={options} />
```
[the remark this answers is not in the document]
Comment (melkuo) [reply components/charts/AnnualizedHousingChart.tsx:265]: Not intentional, let's try it and we can always change it if need be!

File: components/charts/utils/styling.ts (hunk 2 above)
Comment (melkuo) [reply components/charts/utils/styling.ts:36]: The newly added charts for Digital Innovation are using them. I created a follow-up task to add them to all: https://github.com/BuildCanada/OutcomeTracker/issues/128
